CREATE TABLE inditex.BRAND(
	ID 		INTEGER AUTO_INCREMENT PRIMARY KEY,
	NAME 		VARCHAR(100)  NOT NULL,
	CODE		VARCHAR(20)  NOT NULL,
	
	CONSTRAINT uk_BRAND_CODE UNIQUE(CODE)		
);

CREATE TABLE inditex.PRODUCT(
	ID 		INTEGER AUTO_INCREMENT PRIMARY KEY,
	NAME 		VARCHAR(100)  NOT NULL,
	CODE		VARCHAR(20)  NOT NULL,
	
	CONSTRAINT uk_PRODUCT_CODE UNIQUE(CODE)		
);

CREATE TABLE inditex.PRICES(
	ID 		INTEGER AUTO_INCREMENT PRIMARY KEY,
	BRAND_ID 	INTEGER NOT NULL,
	START_DATE 	DATETIME NOT NULL,
	END_DATE 	DATETIME,
	PRICE_LIST 	INTEGER NOT NULL,
	PRODUCT_ID	INTEGER NOT NULL,
	PRIORITY	BIT NOT NULL,
	PRICE		FLOAT(10,2) NOT NULL,
	CURR		VARCHAR(10) NOT NULL,
	
	CONSTRAINT `fk_PRICES_BRAND_ID_BRAND` FOREIGN KEY(`BRAND_ID`) REFERENCES `BRAND`(`ID`),
	CONSTRAINT `fk_PRICES_PRODUCT_ID_PRODUCT` FOREIGN KEY(`PRODUCT_ID`) REFERENCES `PRODUCT`(`ID`)		
);
